### ISSUE TITLE
unable to handle kernel NULL pointer dereference

### ISSUE THREAD

**Issue by tosiara** [jonjonarnearne/smi2021#1]
This happens after playing few times and then unlugging the device:

```
[  378.344503] BUG: unable to handle kernel NULL pointer dereference at           (null)
[  378.348823] IP: [<ffffffffa0b1d74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  378.350955] PGD 146274067 PUD 147e80067 PMD 0 
[  378.353097] Oops: 0000 [#1] PREEMPT SMP 
[  378.355680] Modules linked in: md4 md5 nls_utf8 cifs saa7115 smi2021 rfcomm nfsv3 nfs_acl rpcsec_gss_krb5 auth_rpcgss oid_registry nfsv4 ctr ccm xt_pkttype nfs ppdev parport_pc parport fuse fscache lockd vmw_vsock_vmci_transport vsock vmw_vmci sunrpc af_packet ip6t_REJECT xt_tcpudp nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_raw ipt_REJECT iptable_raw xt_CT iptable_filter ip6table_mangle nf_conntrack_netbios_ns nf_conntrack_broadcast nf_conntrack_ipv4 nf_defrag_ipv4 ip_tables xt_conntrack nf_conntrack bnep ip6table_filter ip6_tables x_tables ecb x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm arc4 ath9k mac80211 ath3k snd_hda_codec_realtek snd_hda_codec_hdmi btusb snd_hda_codec_generic crc32_pclmul bluetooth ath9k_common snd_hda_intel ath9k_hw crc32c_intel snd_hda_controller ghash_clmulni_intel
[  378.366013]  ath snd_hda_codec aesni_intel cfg80211 snd_hwdep ablk_helper snd_pcm cryptd snd_seq uvcvideo iTCO_wdt iTCO_vendor_support snd_timer snd_seq_device lpc_ich videobuf2_core v4l2_common r8169 lrw snd sparse_keymap videodev mfd_core mii rfkill gf128mul mei_me shpchp soundcore mei videobuf2_vmalloc videobuf2_memops sr_mod cdrom glue_helper i2c_i801 aes_x86_64 pcspkr joydev serio_raw button wmi toshiba_bluetooth battery video ac sg dm_mod autofs4 btrfs raid6_pq xor radeon ttm drm_kms_helper drm xhci_hcd i2c_algo_bit thermal processor thermal_sys scsi_dh_rdac scsi_dh_emc scsi_dh_alua scsi_dh_hp_sw scsi_dh
[  378.380560] CPU: 0 PID: 1959 Comm: vlc Not tainted 3.17.0-rc6-21-desktop+ #1
[  378.383590] Hardware name: TOSHIBA SATELLITE L850/Type2 - Board Product Name1, BIOS 6.80 10/01/2013
[  378.387255] task: ffff8800a9c844d0 ti: ffff8800a8410000 task.ti: ffff8800a8410000
[  378.390382] RIP: 0010:[<ffffffffa0b1d74f>]  [<ffffffffa0b1d74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  378.393562] RSP: 0018:ffff8800a8413d70  EFLAGS: 00010246
[  378.397264] RAX: ffff880145a5dc40 RBX: ffff880145a5dc40 RCX: 0000000000000040
[  378.400443] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000000000000000
[  378.403626] RBP: ffff8800a8413da0 R08: 0000000000000001 R09: 0000000000000000
[  378.406786] R10: ffff880147e70000 R11: ffff880147da8000 R12: ffff880147d72008
[  378.409930] R13: 0000000000000003 R14: ffff880147d72e18 R15: ffff880148a7b960
[  378.413060] FS:  00007fab6c147700(0000) GS:ffff88014ec00000(0000) knlGS:0000000000000000
[  378.416377] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  378.419548] CR2: 0000000000000000 CR3: 0000000146614000 CR4: 00000000000407f0
[  378.422754] Stack:
[  378.425935]  ffff880148a7b960 ffff8800a8413d90 ffffffff814771ef 0000000000000080
[  378.429199]  ffff8800a4abc600 ffff880147d72000 ffff8800a8413dc8 ffffffffa0b1e090
[  378.432463]  ffff880147d72bb0 ffff880147d72000 ffff880147d72e20 ffff8800a8413e00
[  378.435730] Call Trace:
[  378.439248]  [<ffffffff814771ef>] ? urb_destroy+0x1f/0x30
[  378.442497]  [<ffffffffa0b1e090>] smi2021_stop+0x80/0x90 [smi2021]
[  378.445748]  [<ffffffffa0b1e8a9>] stop_streaming+0x29/0xe0 [smi2021]
[  378.449244]  [<ffffffffa04a9626>] __vb2_queue_cancel+0x26/0x180 [videobuf2_core]
[  378.452535]  [<ffffffffa04acda5>] vb2_queue_release+0x15/0x30 [videobuf2_core]
[  378.455814]  [<ffffffffa04ace21>] _vb2_fop_release+0x61/0xa0 [videobuf2_core]
[  378.459041]  [<ffffffffa04ace85>] vb2_fop_release+0x25/0x50 [videobuf2_core]
[  378.462344]  [<ffffffffa045940f>] v4l2_release+0x2f/0x70 [videodev]
[  378.465648]  [<ffffffff811b1ab6>] __fput+0xc6/0x1d0
[  378.468953]  [<ffffffff811b1bf9>] ____fput+0x9/0x10
[  378.472229]  [<ffffffff81077067>] task_work_run+0x97/0xd0
[  378.475495]  [<ffffffff81002f21>] do_notify_resume+0x61/0xa0
[  378.478761]  [<ffffffff8162b52a>] int_signal+0x12/0x17
[  378.482103] Code: e8 97 6f 67 e0 48 85 c0 48 89 c3 74 5f c6 00 01 44 88 68 01 45 31 c9 49 8b 3c 24 41 b8 01 00 00 00 b9 40 00 00 00 ba 01 00 00 00 <8b> 37 c7 44 24 10 e8 03 00 00 c7 44 24 08 02 00 00 00 48 89 04 
[  378.489253] RIP  [<ffffffffa0b1d74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  378.492716]  RSP <ffff8800a8413d70>
[  378.496056] CR2: 0000000000000000
[  378.512267] ---[ end trace f1184745d61b846f ]---
[  380.185744] usb 3-2: USB disconnect, device number 11
```

**Comment by jonjonarnearne** [comment]
This issue should be fixed by the latest commit

**Comment by tosiara** [comment]
Issue is still there:

```
[  245.248543] BUG: unable to handle kernel NULL pointer dereference at           (null)
[  245.250770] IP: [<ffffffffa0aee74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  245.252991] PGD 3331b067 PUD 34905067 PMD 0 
[  245.255220] Oops: 0000 [#1] PREEMPT SMP 
[  245.257454] Modules linked in: saa7115 smi2021 rfcomm nfsv3 nfs_acl rpcsec_gss_krb5 auth_rpcgss oid_registry nfsv4 ctr ccm xt_pkttype nfs ppdev parport_pc parport fscache lockd af_packet sunrpc fuse vmw_vsock_vmci_transport vsock vmw_vmci ip6t_REJECT xt_tcpudp nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_raw ipt_REJECT iptable_raw xt_CT iptable_filter ip6table_mangle nf_conntrack_netbios_ns nf_conntrack_broadcast nf_conntrack_ipv4 nf_defrag_ipv4 ip_tables xt_conntrack nf_conntrack ip6table_filter bnep ip6_tables x_tables ecb snd_hda_codec_realtek arc4 x86_pkg_temp_thermal snd_hda_codec_hdmi snd_hda_codec_generic intel_powerclamp snd_hda_intel ath9k snd_hda_controller snd_hda_codec mac80211 coretemp ath3k kvm_intel kvm snd_hwdep btusb bluetooth snd_pcm snd_seq ath9k_common snd_timer ath9k_hw snd_seq_device
[  245.268356]  snd ath cfg80211 iTCO_wdt uvcvideo joydev iTCO_vendor_support videobuf2_core crc32_pclmul sr_mod soundcore crc32c_intel mei_me v4l2_common videodev serio_raw ghash_clmulni_intel aesni_intel ablk_helper cryptd lrw gf128mul glue_helper aes_x86_64 r8169 mei pcspkr videobuf2_vmalloc videobuf2_memops mii lpc_ich mfd_core cdrom i2c_i801 sparse_keymap rfkill toshiba_bluetooth video shpchp battery wmi ac button sg dm_mod autofs4 btrfs raid6_pq xor radeon ttm drm_kms_helper xhci_hcd drm i2c_algo_bit thermal processor thermal_sys scsi_dh_rdac scsi_dh_emc scsi_dh_alua scsi_dh_hp_sw scsi_dh
[  245.285608] CPU: 2 PID: 1950 Comm: vlc Not tainted 3.17.0-rc6-21-desktop+ #1
[  245.290047] Hardware name: TOSHIBA SATELLITE L850/Type2 - Board Product Name1, BIOS 6.80 10/01/2013
[  245.293910] task: ffff8800a83f23d0 ti: ffff8800a9fa8000 task.ti: ffff8800a9fa8000
[  245.298399] RIP: 0010:[<ffffffffa0aee74f>]  [<ffffffffa0aee74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  245.301920] RSP: 0018:ffff8800a9fabd70  EFLAGS: 00010246
[  245.305329] RAX: ffff88014604b180 RBX: ffff88014604b180 RCX: 0000000000000040
[  245.308681] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000000000000000
[  245.311979] RBP: ffff8800a9fabda0 R08: 0000000000000001 R09: 0000000000000000
[  245.315424] R10: ffff880147ab8000 R11: ffff880147a60000 R12: ffff88014651e008
[  245.318814] R13: 0000000000000003 R14: ffff88014651ee18 R15: ffff880034de4ba0
[  245.322127] FS:  00007fa5e3cdc700(0000) GS:ffff88014ec80000(0000) knlGS:0000000000000000
[  245.325477] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  245.328891] CR2: 0000000000000000 CR3: 0000000033198000 CR4: 00000000000407e0
[  245.332333] Stack:
[  245.335680]  ffff880034de4ba0 ffff8800a9fabd90 ffffffff814771ef 0000000000000080
[  245.339158]  ffff8800334a4200 ffff88014651e000 ffff8800a9fabdc8 ffffffffa0aef090
[  245.342688]  ffff88014651ebb0 ffff88014651e000 ffff88014651ee20 ffff8800a9fabe00
[  245.346150] Call Trace:
[  245.349539]  [<ffffffff814771ef>] ? urb_destroy+0x1f/0x30
[  245.353018]  [<ffffffffa0aef090>] smi2021_stop+0x80/0x90 [smi2021]
[  245.356516]  [<ffffffffa0aef8a9>] stop_streaming+0x29/0xe0 [smi2021]
[  245.359959]  [<ffffffffa04e4626>] __vb2_queue_cancel+0x26/0x180 [videobuf2_core]
[  245.363444]  [<ffffffffa04e7da5>] vb2_queue_release+0x15/0x30 [videobuf2_core]
[  245.367017]  [<ffffffffa04e7e21>] _vb2_fop_release+0x61/0xa0 [videobuf2_core]
[  245.370550]  [<ffffffffa04e7e85>] vb2_fop_release+0x25/0x50 [videobuf2_core]
[  245.374062]  [<ffffffffa04a840f>] v4l2_release+0x2f/0x70 [videodev]
[  245.377620]  [<ffffffff811b1ab6>] __fput+0xc6/0x1d0
[  245.381155]  [<ffffffff811b1bf9>] ____fput+0x9/0x10
[  245.384608]  [<ffffffff81077067>] task_work_run+0x97/0xd0
[  245.388057]  [<ffffffff81002f21>] do_notify_resume+0x61/0xa0
[  245.391518]  [<ffffffff8162b52a>] int_signal+0x12/0x17
[  245.394941] Code: e8 97 5f 6a e0 48 85 c0 48 89 c3 74 5f c6 00 01 44 88 68 01 45 31 c9 49 8b 3c 24 41 b8 01 00 00 00 b9 40 00 00 00 ba 01 00 00 00 <8b> 37 c7 44 24 10 e8 03 00 00 c7 44 24 08 02 00 00 00 48 89 04 
[  245.402569] RIP  [<ffffffffa0aee74f>] smi2021_set_mode.isra.4+0x4f/0xa0 [smi2021]
[  245.406391]  RSP <ffff8800a9fabd70>
[  245.410135] CR2: 0000000000000000
[  245.428441] ---[ end trace 252ed4e2f0a462c2 ]---
```

To reproduce:
1. start play in VLC
2. unplug device
3. plug device back
4. stop play in vlc
5. exception happens

**Comment by jonjonarnearne** [comment]
Ok, I'm working on a rewrite. I'll open the issue for now.

**Comment by jonjonarnearne** [comment]
I just pushed a major rewrite of the driver.
This bug should be gone now.

Please test it if you have the time :)

**Comment by tosiara** [comment]
Still crashes. Stack seems different than previous

What I did:
1. insmod new built smi2021.ko
2. plug device
3. start vlc
4. unplug device plug it back
5. stop vlc
6. crash

```
[  103.627257] usbcore: registered new interface driver smi2021
[  113.325496] usb 3-1: new high-speed USB device number 3 using xhci_hcd
[  113.490573] usb 3-1: New USB device found, idVendor=1c88, idProduct=0007
[  113.490585] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  113.490591] usb 3-1: Product: SM-USB 007
[  113.490596] usb 3-1: Manufacturer: Somagic, Inc.
[  113.490600] usb 3-1: SerialNumber: SMBL007
[  113.491093] usb 3-1: Looking for: smi2021_3f.bin
[  113.491162] usb 3-1: Looking for: smi2021_3e.bin
[  113.520656] usb 3-1: Found firmware for 0x003e
[  113.531211] usb 3-1: USB disconnect, device number 3
[  113.815033] usb 3-1: new high-speed USB device number 4 using xhci_hcd
[  113.980403] usb 3-1: New USB device found, idVendor=1c88, idProduct=003e
[  113.980413] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  113.980419] usb 3-1: Product:  SMI Grabber Dev
[  113.980423] usb 3-1: Manufacturer:  Somagic, Inc.  
[  113.980428] usb 3-1: SerialNumber: SMIVIDEO3E9876543210
[  113.996943] saa7115 8-004a: gm7113c found @ 0x94 (smi2021)
[  114.017006] smi2021 3-1:1.0: V4L2 device registered as video1
[  137.162881] smi2021 3-1:1.0: queue_setup: buffer count 4, each 696960 bytes
[  137.167715] smi2021 3-1:1.0: allocating urbs...
[  137.167816] smi2021 3-1:1.0: 16 urbs of 30720 bytes, allocated
[  144.235894] usb 3-1: USB disconnect, device number 4
[  144.235990] smi2021 3-1:1.0: killing 16 urbs...
[  144.235993] smi2021 3-1:1.0: all urbs killed
[  144.235994] smi2021 3-1:1.0: freeing 16 urb buffers...
[  144.236000] smi2021 3-1:1.0: all urb buffers freed
[  144.236001] smi2021 3-1:1.0: clear_queue called
[  144.236005] smi2021 3-1:1.0: buffer [ffff8800a4a5a000/1] aborted
[  144.236008] smi2021 3-1:1.0: buffer [ffff880034554800/2] aborted
[  144.236010] smi2021 3-1:1.0: buffer [ffff880034556c00/3] aborted
[  144.236012] smi2021 3-1:1.0: buffer [ffff880034554400/0] aborted
[  144.236013] smi2021 3-1:1.0: returning from clear_queue
[  148.154258] usb 3-1: new high-speed USB device number 5 using xhci_hcd
[  148.319118] usb 3-1: New USB device found, idVendor=1c88, idProduct=0007
[  148.319122] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  148.319124] usb 3-1: Product: SM-USB 007
[  148.319125] usb 3-1: Manufacturer: Somagic, Inc.
[  148.319126] usb 3-1: SerialNumber: SMBL007
[  148.319319] usb 3-1: Looking for: smi2021_3f.bin
[  148.319336] usb 3-1: Looking for: smi2021_3e.bin
[  148.319357] usb 3-1: Found firmware for 0x003e
[  148.329307] usb 3-1: USB disconnect, device number 5
[  148.612771] usb 3-1: new high-speed USB device number 6 using xhci_hcd
[  148.777774] usb 3-1: New USB device found, idVendor=1c88, idProduct=003e
[  148.777777] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  148.777779] usb 3-1: Product:  SMI Grabber Dev
[  148.777780] usb 3-1: Manufacturer:  Somagic, Inc.  
[  148.777782] usb 3-1: SerialNumber: SMIVIDEO3E9876543210
[  148.790020] saa7115 9-004a: gm7113c found @ 0x94 (smi2021)
[  148.807655] smi2021 3-1:1.0: V4L2 device registered as video2
[  166.231983] general protection fault: 0000 [#1] PREEMPT SMP 
[  166.232029] Modules linked in: smi2021(O) saa7115 rfcomm nfsv3 nfs_acl rpcsec_gss_krb5 auth_rpcgss oid_registry nfsv4 ctr ccm xt_pkttype ppdev parport_pc parport fuse nfs fscache lockd sunrpc vmw_vsock_vmci_transport vsock vmw_vmci af_packet ip6t_REJECT xt_tcpudp nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_raw ipt_REJECT iptable_raw xt_CT iptable_filter ip6table_mangle nf_conntrack_netbios_ns nf_conntrack_broadcast nf_conntrack_ipv4 nf_defrag_ipv4 ip_tables xt_conntrack nf_conntrack bnep ip6table_filter ip6_tables x_tables arc4 ath9k mac80211 x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm ath9k_common ath9k_hw ath cfg80211 ath3k ecb btusb bluetooth snd_hda_codec_realtek snd_hda_codec_generic snd_hda_codec_hdmi snd_hda_intel snd_hda_controller snd_hda_codec uvcvideo crc32_pclmul crc32c_intel
[  166.232322]  snd_hwdep snd_pcm ghash_clmulni_intel snd_seq snd_timer snd_seq_device snd iTCO_wdt iTCO_vendor_support aesni_intel ablk_helper cryptd videobuf2_core r8169 v4l2_common videodev pcspkr sparse_keymap rfkill lrw gf128mul glue_helper aes_x86_64 i2c_i801 joydev serio_raw soundcore mii sr_mod videobuf2_vmalloc videobuf2_memops lpc_ich mfd_core cdrom mei_me mei shpchp toshiba_bluetooth wmi video battery ac button sg dm_mod autofs4 btrfs raid6_pq xor radeon ttm drm_kms_helper drm xhci_hcd i2c_algo_bit thermal processor thermal_sys scsi_dh_rdac scsi_dh_emc scsi_dh_alua scsi_dh_hp_sw scsi_dh
[  166.232550] CPU: 1 PID: 1919 Comm: vlc Tainted: G           O   3.17.0-rc6-21-desktop+ #1
[  166.232574] Hardware name: TOSHIBA SATELLITE L850/Type2 - Board Product Name1, BIOS 6.80 10/01/2013
[  166.232600] task: ffff8800a56ce090 ti: ffff8800345f0000 task.ti: ffff8800345f0000
[  166.232622] RIP: 0010:[<ffffffff8140d121>]  [<ffffffff8140d121>] __dev_printk+0x21/0x90
[  166.232650] RSP: 0018:ffff8800345f3d40  EFLAGS: 00010206
[  166.232666] RAX: 342e313a00000005 RBX: ffff8800331f4788 RCX: ffff8801c6763f80
[  166.232686] RDX: ffff8800345f3d50 RSI: ffff880033567c30 RDI: ffffffff819f97f6
[  166.232706] RBP: ffff8800345f3d40 R08: 2e706f746b736564 R09: ffff8800345f3d50
[  166.232727] R10: ffffea0002512848 R11: 00000000ffffffff R12: ffff8800331f4000
[  166.232747] R13: ffff8800331f4820 R14: ffff8800a8de9798 R15: ffff880034deeba0
[  166.232768] FS:  00007f5842240700(0000) GS:ffff88014ec40000(0000) knlGS:0000000000000000
[  166.232791] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  166.232808] CR2: 00007f584223cc28 CR3: 00000000a79d4000 CR4: 00000000000407e0
[  166.232828] Stack:
[  166.232835]  ffff8800345f3da8 ffffffff8140d4e7 ffffffffa0b0407f ffff8800345f3d60
[  166.232861]  0000000000000010 ffff8800345f3db8 ffff8800345f3d78 0000000000000052
[  166.232887]  0000000000000001 0000000000000001 ffff8801c6763f80 0000000000000052
[  166.232912] Call Trace:
[  166.232923]  [<ffffffff8140d4e7>] _dev_info+0x57/0x60
[  166.232940]  [<ffffffffa0b003e6>] smi2021_release+0x26/0x70 [smi2021]
[  166.232965]  [<ffffffffa0455f39>] v4l2_device_release+0x19/0x20 [videodev]
[  166.232990]  [<ffffffffa04563e4>] v4l2_device_put+0x24/0x30 [videodev]
[  166.233012]  [<ffffffffa04507a3>] v4l2_device_release+0xa3/0xe0 [videodev]
[  166.233033]  [<ffffffff8140c55d>] device_release+0x2d/0xa0
[  166.233051]  [<ffffffff813118e7>] kobject_cleanup+0x77/0x1b0
[  166.233069]  [<ffffffff81311790>] kobject_put+0x30/0x60
[  166.233085]  [<ffffffff8140c832>] put_device+0x12/0x20
[  166.233103]  [<ffffffffa044f425>] v4l2_release+0x45/0x70 [videodev]
[  166.233123]  [<ffffffff811b1ab6>] __fput+0xc6/0x1d0
[  166.233138]  [<ffffffff811b1bf9>] ____fput+0x9/0x10
[  166.233154]  [<ffffffff81077067>] task_work_run+0x97/0xd0
[  166.233171]  [<ffffffff81002f21>] do_notify_resume+0x61/0xa0
[  166.233188]  [<ffffffff8162b52a>] int_signal+0x12/0x17
[  166.233204] Code: fe ff ff c9 c3 0f 1f 44 00 00 55 48 85 f6 49 89 d1 48 89 e5 74 65 4c 8b 46 50 4d 85 c0 74 2b 48 8b 86 90 00 00 00 48 85 c0 74 2f <48> 8b 08 0f be 7f 01 48 c7 c2 1f 8d a3 81 31 c0 83 ef 30 e8 87 
[  166.233340] RIP  [<ffffffff8140d121>] __dev_printk+0x21/0x90
[  166.233358]  RSP <ffff8800345f3d40>
[  166.237233] ---[ end trace c08e9337e4a60723 ]---
```

**Comment by jonjonarnearne** [comment]
Ok, thanks.
That is a different crash, I'll have to try to reproduce that.

**Comment by jonjonarnearne** [comment]
I've completed some small changes on the code, and I'm not able to reproduce this error anymore.
Could you give it a test?

**Comment by tosiara** [comment]
Now that is fixed
